# Centralised configuration for Snakefile

samples:
  - sample1
  - sample2
  - sample3

workdir: "results"

reference: "ref/genome.fa"

mem_mb:
  default: 4000
  align: 8000
  call: 6000
  process: 8000      # same value as align (or adjust)

threads:
  default: 1
  align: 4
  call: 2
  process: 4

params:
  align_extra: ""
  call_extra: ""
